image: Visual Studio 2022

build_script:
  - cmake -S . -B _build -G "Visual Studio 17 2022" -DBUILD_TESTS=ON
  - cmake --build _build --config Release

test_script:
  - ctest --test-dir _build -C Release --output-on-failure
